[package]
name = "ink"
version.workspace = true
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition.workspace = true
rust-version = "1.63"

license.workspace = true
readme = "README.md"
repository.workspace = true
documentation = "https://docs.rs/ink"
homepage.workspace = true
description = "[ink!] Rust based eDSL for writing smart contracts for Substrate"
keywords.workspace = true
categories.workspace = true
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_env = { workspace = true }
ink_storage = { workspace = true }
ink_primitives = { workspace = true }
ink_metadata = { workspace = true, optional = true }
ink_prelude = { workspace = true }
ink_macro = { workspace = true }

scale = { package = "parity-scale-codec", workspace = true }
derive_more = { workspace = true, features = ["from"] }

[dev-dependencies]
ink_ir = { workspace = true, default-features = true }
ink_metadata = { workspace = true }

trybuild = { workspace = true, features = ["diff"] }
# Required for the doctest of `env_access::EnvAccess::instantiate_contract`
scale-info = { workspace = true, features = ["derive"] }

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_prelude/std",
    "ink_primitives/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_macro/std",
    "scale/std",
]
# Enable contract debug messages via `debug_print!` and `debug_println!`.
ink-debug = [
    "ink_env/ink-debug",
]

show-codegen-docs = []

# Disable the ink! provided global memory allocator.
no-allocator = ["ink_env/no-allocator"]

# Configurable sizes of the static buffer
2GB-buffer = ["ink_env/2GB-buffer"]
1GB-buffer = ["ink_env/1GB-buffer"]
512MB-buffer = ["ink_env/512MB-buffer"]
128MB-buffer = ["ink_env/128MB-buffer"]
16MB-buffer = ["ink_env/16MB-buffer"]
1MB-buffer = ["ink_env/1MB-buffer"]
512kB-buffer = ["ink_env/512kB-buffer"]
128kB-buffer = ["ink_env/128kB-buffer"]
